// <auto-generated />
namespace LocalDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class _1aVersao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1aVersao));
        
        string IMigrationMetadata.Id
        {
            get { return "201910261726470_1aVersao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
